---
- hosts: ircdnodes
  user: ircd
  gather_facts: no
  tasks:
  - name: push new configs to all ircd nodes
    action: shell cd ~/entropynet/config && git pull
    notify:
    - rehash ircds
  handlers:
    - name: rehash ircds
      action: shell pkill -HUP -F ~/ircd/etc/ircd.pid

