---
- hosts: ircdnodes
  user: ircd
  gather_facts: no
  tasks:
  - name: Copy SSL certificate to correct directory on ircd nodes
    copy:
      src: '/etc/ssl/localcerts/namecheap/entropynet.net-2019/irc.entropynet.net.crt'
      dest: '/home/ircd/ssl/entropynet/namecheap/irc.entropynet.net.crt'
      backup: yes
  - name: Copy SSL key to correct directory on ircd nodes
    copy:
      src: '/etc/ssl/localcerts/namecheap/entropynet.net-2019/irc.entropynet.net.key'
      dest: '/home/ircd/ssl/entropynet/namecheap/irc.entropynet.net.key'
      backup: yes
  - name: Rehash ircdnodes
    shell: /home/ircd/unrealircd/unrealircd reloadtls
